###

# curl -X POST "https://pixelate.app/api/posts/2" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "X-CSRF-TOKEN: " -d "{\"caption\":\"Here\",\"imageUrl\":\"https://picsum.photos/400/300\",\"location\":\"Dusseldorf\"}"
POST https://pixelate.app/api/posts/2
accept: application/json
X-CSRF-TOKEN:
Content-Type: application/json

{
    "caption": "Here",
    "imageUrl": "https://picsum.photos/400/300",
    "location": "Dusseldorf"
}

###

